RIC/RIC/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
# from . import views

admin.site.site_header = "RIC Admin"
admin.site.site_title = "RIC Admin Portal"
admin.site.index_title = "Welcome to RIC ADMIN PORTAL"


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    # path('microsoft-login/', views.microsoft_login.as_view(), name='microsoft_login'),

    path('', include('home.urls')),
    path('editor/', include('editor.urls')),
    path('rc/', include('prev_edition.urls')),
    path('profile/', include('members.urls')),
    path('event/', include('event.urls')),
    path('team/', include('team.urls')),
    path('faq/', include('faq.urls')),
    path('sponsor/', include('sponsor.urls')),
    path('schedule/', include('schedule.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

RIC/event/urls.py
from django.urls import path, reverse_lazy
from . import views
from .views import merchandise_view


app_name='event'
urlpatterns = [
    # path('<int:pk>', views.ProductDetail.as_view(),name='detail'),
    
    # path('workshopspeaker/<int:pk>', views.SpeakerDetail.as_view(),name='workshopspeakerspeaker'),
    path('speaker/', views.DeptSpeakerListView.as_view(),name='speakerlist'),
    path('merch/', merchandise_view,name='merch'),
    path('speaker/<int:pk>', views.SpeakerDetailView.as_view(),name='speakerdetail'),
    path('deptspeaker/<int:pk>', views.DeptSpeakerDetailView.as_view(),name='deptspeakerdetail'),
    path('<slug:name>/', views.ProductDetail.as_view(),name='detail'),
]

RIC/event/models.py
from django.db import models
from django_ckeditor_5.fields import CKEditor5Field
from members.models import Dept

# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=50)
    pic = models.ImageField(upload_to="event")
    subtitle = models.CharField(max_length=50)
    content = CKEditor5Field()

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name

class Speaker(models.Model):
    name = models.CharField(max_length=50)
    subtitle = CKEditor5Field()
    pic = models.ImageField(upload_to='speakers', height_field=None, width_field=None, max_length=None)
    content = CKEditor5Field()

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name

class DeptSpeaker(models.Model):
    name = models.CharField(max_length=150)
    subtitle = CKEditor5Field()
    dept = models.ForeignKey(Dept, on_delete=models.CASCADE,default=None,null=True,blank=True)
    pic = models.ImageField(upload_to='dept_speakers', height_field=None, width_field=None, max_length=None)
    content = CKEditor5Field()

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name

RIC/event/views.py
from django.shortcuts import render
from .models import Product,Speaker,DeptSpeaker
from members.models import Workshop
from django.views.generic import TemplateView,ListView, DetailView, CreateView, UpdateView,DeleteView
from django.shortcuts import get_object_or_404
# Create your views here.

class ProductDetail(DetailView):
    model = Product
    template_name='event/detail.html'

    def get_object(self, queryset=None):
        name = self.kwargs.get('name').upper().replace('-', ' ')
        return get_object_or_404(Product, name=name)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["workshop_list"] = Workshop.objects.all()
        context['event'] = self.object
        return context


class SpeakerDetailView(DetailView):
    model = Speaker
    template_name='event/institutespeakerdetail.html'


class DeptSpeakerListView(ListView):
    model = Speaker
    template_name = "event/speaker.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["speaker_list"] = Speaker.objects.all()
        context["dept_speaker_list"] = DeptSpeaker.objects.all()
        return context


class DeptSpeakerDetailView(DetailView):
    model = DeptSpeaker
    template_name='event/institutespeakerdetail.html'

def merchandise_view(request):
    return render(request, 'event/merchandise.html')

RIC/event/templates/event/institutespeakerdetail.html
{% extends 'base.html' %} {% load static %} {% block banner %}
<section>
    <div class="lgx-banner lgx-banner-music">
        <div class="lgx-banner-style">
            <div class="lgx-inner lgx-inner-fixed">
                <div class="container">
                    <div class="row">
                        <center><b>
                <h2>About The Speaker</h2>
              </b></center>
                    </div>
                </div>
            </div>
            <!--//.ROW-->
        </div>
        <!-- //.CONTAINER -->
    </div>
    <!-- //.INNER -->
    </div>
    </div>
</section>
<div class="container" style="padding: 100px 0;">
    <!--<h2 style="text-align: center;">Stay tuned and patiently await the upcoming speakers !</h2>-->
</div>
{% endblock banner %} 
{% block content %}
<main>
    <div class="lgx-post-wrapper">
        <!--News-->
        <section>
            <div class="container">
                <div class="row">
                    <div class="col-xs-12">
                        <article>
                            <header>
                                        <h1 class="title">{{object}}</h1>
                                <figure>
                                    <img src="{{object.pic.url}}" alt="New" />
                                </figure>
                                <div class="text-area">
                                    <div class="speaker-info">
                                        <h2>{{object.subtitle|safe|linebreaks}}</h2>

                                    </div>
                                </div>
                            </header>
                            <div class="container">
                                <div class="row">
                                    <div class="col-xs-12">
                                        <div class="lgx-heading lgx-heading-blue">
                                            <h3 class="subheading"><b>About the Talk</b></h3>

                                            <br>
                                            <section>

                                                <p class="text" align="justify">
                                                    {{object.content|safe|linebreaks}}
                                                </p>
                                            </section>

                                        </div>
                                    </div>
                                    <section>


                                        <!--blockquote>
                                    <p>Suspendisse hendrerit et sapien ut pretium. Aenean nulla ipsum, facilisis eu porta non, rutrum sit amet nibh. Quisque id diam feugiat, pharetra arcu eget, bibendum tortor. </p>
                                    <footer>Someone famous in <cite title="Source Title">Source Title</cite></footer>
                                </blockquote>
                                <blockquote>
                                    Suspendisse hendrerit et sapien ut pretium. Aenean nulla ipsum, facilisis eu porta non, rutrum sit amet nibh. Quisque id diam feugiat, pharetra arcu eget, bibendum tortor.
                                </blockquote>
                            </section>
                            <footer>
                                <div class="row">
                                    <div class="col-xs-12">
                                        <h4 class="title">Share</h4>
                                        <div class="lgx-share">
                                            <ul class="list-inline lgx-social">
                                                <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                                                <li><a href="#"><i class="fa fa-facebook-f" aria-hidden="true"></i></a></li>
                                                <li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
                                                <li><a href="#"><i class="fa fa-youtube-play" aria-hidden="true"></i></a></li>
                                                <li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </footer-->
                        </article>
                        </div>
                        </div>
                    </div>
                    <!-- //.CONTAINER -->
                    </section>
                    <!--News END-->
                </div>
</main>

{% endblock content %}

RIC/event/templates/event/institutespeakerlist.html
{% extends 'base.html' %} {% load static %} {% block banner %}
<script>
    @import url('https://fonts.googleapis.com/css2?family=Alfa+Slab+One&display=swap');

        .waviy {
          position: relative;
          -webkit-box-reflect: below -20px linear-gradient(transparent, rgba(0,0,0,.2));
          font-size: 60px;
        }
        .waviy span {
          font-family: 'Alfa Slab One', cursive;
          position: relative;
          display: inline-block;
          color: #fff;
          text-transform: uppercase;
          animation: waviy 2.5s infinite;
          animation-delay: calc(.2s * var(--i));

        }
        @keyframes waviy {
          0%,40%,100% {
            transform: translateY(0)
          }
          20% {
            transform: translateY(-20px)
          }
        }
</script>

<section>
    <div class="lgx-banner lgx-banner-music">
        <div class="lgx-banner-style">
            <div class="lgx-inner lgx-inner-fixed">
                <div class="container">
                    <div class="row">
                        <center><b>
                <h2>Speakers</h2>
              </b></center>
                    </div>
                </div>
            </div>
            <!--//.ROW-->
        </div>
        <!-- //.CONTAINER -->
    </div>
    <!-- //.INNER -->
    </div>
    </div>
</section>

{% endblock banner %} {% block content %}

<!-- this is temporary for upcoming speakers -->
<div class="waviy">
   <span style="--i:1">c</span>
   <span style="--i:2">o</span>
   <span style="--i:3">m</span>
   <span style="--i:4">i</span>
   <span style="--i:5">n</span>
   <span style="--i:6">g</span>
   <span style="--i:7">s</span>
   <span style="--i:8">o</span>
   <span style="--i:9">o</span>
   <span style="--i:10">n</span>
  </div>


<!--<div class="row">-->
<!--    <div class="row">-->
<!--        <div class="col-xs-12">-->
<!--            <div class="sponsors-area">-->
<!--                {% for i in institutespeaker_list %}-->
<!--                {% if i.id == 22 %}-->
<!--                <div class="single">-->
<!--                    <a class="" href="{% url 'event:speakerdetail' i.id %}"><img src="{{i.pic.url}}" style="border-radius: 50%; height: 25rem; width: 25rem; border: 2px solid black;" alt="events" /></a>-->
<!--                    <div class="speaker-info">-->
<!--                        <h5 class="font-weight-bold mt-4 mb-3">-->
<!--                            <p class="text-uppercase"><strong>{{i.name}}<br></strong></p>-->
<!--                            <p><strong>{{i.position}}</strong></p>-->
<!--                        </h5>-->
<!--                    </div>-->
<!--                </div>-->
<!--                {% endif %}-->
<!--                {% endfor %}-->


<!--            </div>-->
<!--        </div>-->
        <!--//col-->
<!--    </div>-->
<!--</div>-->
<!--<div class="row">-->
<!--    <div class="row">-->
<!--        <div class="col-xs-12">-->
<!--            <div class="sponsors-area">-->
<!--                {% for i in institutespeaker_list %}-->
<!--                {% if i.id != 22 and i.id <= 9 %}-->
<!--                <div class="single">-->
<!--                    <a class="" href="{% url 'event:speakerdetail' i.id %}"><img src="{{i.pic.url}}" style="border-radius: 50%; height: 25rem; width: 25rem; border: 2px solid black;" alt="events" /></a>-->
<!--                    <div class="speaker-info">-->
<!--                        <h5 class="font-weight-bold mt-4 mb-3">-->
<!--                            <p class="text-uppercase"><strong>{{i.name}}<br></strong></p>-->
<!--                            <p><strong>{{i.position}}</strong></p>-->
<!--                        </h5>-->
<!--                    </div>-->
<!--                </div>-->
<!--                {% endif %}-->
<!--                {% endfor %}-->


<!--            </div>-->
<!--        </div>-->
        <!--//col-->
<!--    </div>-->
<!--</div>-->
<!--<div class="row">-->
<!--    <div class="row">-->
<!--        <div class="col-xs-12">-->
<!--            <div class="sponsors-area">-->
<!--                {% for i in institutespeaker_list %}-->
<!--                {% if i.id != 22 and i.id > 9 %}-->
<!--                <div class="single">-->
<!--                    <a class="" href="{% url 'event:speakerdetail' i.id %}"><img src="{{i.pic.url}}" style="border-radius: 50%; height: 25rem; width: 25rem; border: 2px solid black;" alt="events" /></a>-->
<!--                    <div class="speaker-info">-->
<!--                        <h5 class="font-weight-bold mt-4 mb-3">-->
<!--                            <p class="text-uppercase"><strong>{{i.name}}<br></strong></p>-->
<!--                            <p><strong>{{i.position}}</strong></p>-->
<!--                        </h5>-->
<!--                    </div>-->
<!--                </div>-->
<!--                {% endif %}-->
<!--                {% endfor %}-->


<!--            </div>-->
<!--        </div>-->
        <!--//col-->
<!--    </div>-->
<!--</div>-->
{% endblock content %}

RIC/event/templates/event/merchandise.html
{% extends 'base.html' %} {% load static %}
{% block css %}
<style>
    .merch-banner {
        width: 100vw;
        height: 26vw;
        background-image: url('/static/home/assets/img/merch-bg.png');
        background-repeat: no-repeat;
        background-position: center;
        background-size: 100vw 26vw;
    }

    /* @media screen and (max-width:767px) {
        .merch-banner {
            height: 35vw;
            background-size: 100vw 35vw;
            margin-top: 0;
        }
    } */

    .custom-shape {
        position: relative;
        width: 16.2vw;
        background-color: #fefbef;
        height: 4.7vw;
        clip-path: polygon(0 0, 100% 0, 100% 71%, 89% 100%, 0 100%);
        display: flex;
        align-items: center;
        justify-content: center;
        border-radius: 0.5vw;
        transition: background-color 0.3s ease;
    }

    .custom-shape:hover {
        background-color: black;
    }

    .border-span {
        width: 16vw;
        height: 4.5vw;
        clip-path: polygon(0 0, 100% 0, 100% 71%, 89% 100%, 0 100%);
        background-color: #013a67;
        border-radius: 0.4vw;
        align-content: center;
        transition: background-color 0.3s ease;
    }

    .registration-tab {
        color: #fefbef;
        font-size: 2.1vw;
        font-family: 'Lato', sans-serif;
        transition: color 0.3s ease;
    }

    .custom-shape:hover .border-span {
        background-color: #ffc812;
    }

    .custom-shape:hover .registration-tab {
        color: black;
    }

    .merch-title {
        position: relative;
        display: inline-block;
        font-size: 7vw;
        font-family: 'LEMON MILK', sans-serif;
        font-weight: 800;
        margin-left: 2vw;
        z-index: 1;
    }

    .outlined-text {
        margin-left: 0.2vw;
        color: transparent;
        -webkit-text-stroke: 0.1vw white;
        z-index: 2;
    }

    .filled-text {
        position: absolute;
        color: #00B0A6;
        z-index: 1;
    }
</style>
{% endblock css %}
{% block banner %}
<div class="merch-banner">
    <img src="{% static 'home/assets/img/merch-sticker1.png' %}" style="width: 11vw;margin-left: 5vw;margin-top: 4vw;">
    <img src="{% static 'home/assets/img/merch-sticker2.png' %}"
        style="width: 8.5vw; margin-top: -10vw; margin-left:2vw">
    <img src="{% static 'home/assets/img/merch-sticker3.png' %}"
        style="width: 19vw; margin-left: -3vw;margin-top: 4.5vw;">
    <img src="{% static 'home/assets/img/merch-sticker4.png' %}" style="width: 8vw;margin-left: 5vw;margin-top: 3.5vw;">
    <div class="merch-title">
        <div class="merch-title">
            <span class="filled-text">MERCH</span>
            <span class="outlined-text">MERCH</span>
        </div>
    </div>
    <!-- <img style="width: 100vw;clip-path: inset(30px 0 0 0); " src="{%static 'home/assets/img/merch-bg.png' %}">  -->
    <!-- <p style="color: #00B0A6;font-size: 7vw;font-weight:1000;font-family: 'Lato',sans-serif;">MERCH</p> -->
</div>
<!-- <img src="{%static 'home/assets/img/merch-bg.png' %}">  -->
<!-- <h1>merch</h1>
<h1>merch</h1>
<h1>merch</h1>
<h1>merch</h1>
<h1>merch</h1>
<h1>merch</h1>
<h1>merch</h1>
<h1>merch</h1>
<h1>merch</h1>
<h1>merch</h1>
<h1>merch</h1>
<h1>merch</h1>
<h1>merch</h1> -->


{% endblock banner %}
{% block content %}
<div class="tshirts"
    style="display: flex;flex-direction: column; gap: 4vw; align-items: center;margin-top: 4.5vw;margin-bottom: 4vw;">
    <img src="{% static 'home/assets/img/tshirt-roundneck.png' %}" style="width: 68vw;">
    <img src="{% static 'home/assets/img/tshirt-roundneck-navy.png' %}" style="width: 68vw;">
    <img src="{% static 'home/assets/img/tshirt-whitepolo.png' %}" style="width: 68vw;">
    <img src="{% static 'home/assets/img/tshirt-navypolo.png' %}" style="width: 68vw;">
    <a href="https://forms.gle/5geob4sXSCddHBnKA" style="text-decoration: none;">
        <div class="custom-shape">
            <span class="border-span">
                <center class="registration-tab">BUY NOW!</center>
            </span>
        </div>
    </a>
</div>
{% endblock content %}

RIC/event/templates/event/speaker.html
{% extends 'base.html' %}
<!--{% load static %}-->
{% block banner %}
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet">
<section>
  <div class="lgx-banner lgx-banner-music">
    <div class="lgx-banner-style">
      <div class="lgx-inner lgx-inner-fixed">
        <div class="container">
          <div class="row">
            <center><b>
                <h2>Speakers</h2>
              </b></center>
          </div>
        </div>
      </div>
      <!--//.ROW-->
    </div>
    <!-- //.CONTAINER -->
  </div>
  <!-- //.INNER -->
  </div>
  </div>
</section>
{% endblock banner %}
{% block content %}

<style>

</style>

<style>
    .speaker *{
        color:black;
        /*height: 10%;*/
    }
    .speaker:hover *{
        color:white;
        height: auto;
    }
    :root {
      --clr-gray-light: #d7dfe2;
      --clr-gray-med: #616b74;
      --clr-gray-dark: #414b56;
      --clr-link: #4d97b2;
      --clr-popular: #ef257a;
      --clr-technology: #651fff;
      --clr-psychology: #e85808;
    }

    .wrapper {
      display: flex;
      flex-wrap: wrap;
      justify-content: center;
    }

    .card {
      overflow: hidden;
      box-shadow: 0px 2px 20px var(--clr-gray-light);
      background: white;
      border-radius: 0.5rem;
      position: relative;
      width: 350px;
      height: auto;
      margin: 1rem;
      transition: 250ms all ease-in-out;
      cursor: pointer;
    }

    .card:hover {
      transform: scale(1.05);
      height: auto;
      box-shadow: 0px 20px 40px var(--clr-gray-dark);
    }

    .banner-img {
      position: absolute;
      /*object-fit: cover;*/
      height: auto;
      width: 100%;
    }

    .category-tag {
      font-size: 1.2rem;
      font-weight: bold;
      color: white;
      background: red;
      padding: 0.5rem 1.3rem 0.5rem 1rem;
      text-transform: uppercase;
      position: absolute;
      z-index: 1;
      top: 1rem;
      border-radius: 0 2rem 2rem 0;
    }
    .category-tag-right {
      font-size: 1.2rem;
      font-weight: bold;
      color: white;
      background: red;
      padding: 0.5rem 1.3rem 0.5rem 1rem;
      text-transform: uppercase;
      position: absolute;
      z-index: 1;
      top: 86%;
      border-radius: 0 2rem 2rem 0;
    }

    .popular {
      background: var(--clr-popular);
    }

    .technology {
      background: var(--clr-technology);
    }

    .psychology {
      background: var(--clr-psychology);
    }

    .card-body {
        z-index: 999;
      margin: 15rem 1rem 1rem 1rem;
    }

    .blog-hashtag {
      font-size: 0.9rem;
      font-weight: 500;
      color: var(--clr-link);
    }

    .blog-title {
      line-height: 1.5rem;
      margin: 1rem 0 0.5rem;
    }

    .blog-description {
      color: var(--clr-gray-med);
      font-size: 0.9rem;
    }

    .card-profile {
      display: flex;
      margin-top: 2rem;
      align-items: center;
    }

    .profile-img {
      width: 60px;
      height: 60px;
      object-fit: cover;
      border-radius: 50%;
    }

    .card-profile-info {
      margin-left: 1rem;
    }

    .profile-name {
      font-size: 1rem;
    }

    .profile-followers {
      color: var(--clr-gray-med);
      font-size: 0.9rem;
    }
</style>

<!-- <br> -->
<!-- <br> -->
<!-- <br> -->
<!-- <br> -->


<!-- this is temporary for upcoming speakers -->
    <!-- <center>
        <div class="waviy mx-auto text-center" >
           <span style="--i:1">t</span>
           <span style="--i:2">o</span>
           <span style="--i:3"> </span>
           <span style="--i:4">b</span>
           <span style="--i:5">e</span>
           <span style="--i:6"> </span>
           <span style="--i:7">a</span>
           <span style="--i:8">n</span>
           <span style="--i:9">n</span>
           <span style="--i:10">o</span>
           <span style="--i:11">u</span>
           <span style="--i:12">n</span>
           <span style="--i:13">c</span>
           <span style="--i:14">e</span>
           <span style="--i:15">d</span>
           <span style="--i:16"> </span>
           <span style="--i:17">s</span>
           <span style="--i:18">o</span>
           <span style="--i:19">o</span>
           <span style="--i:20">n</span>
        </div>
    </center> -->
<br>
<br>
<br>
<br>

<style>
  .brochure-container {
    display: flex;
    justify-content: center;
}

.brochure-tab {
    margin: 0 10px; /* Adjust the spacing between tabs */
    /* background-color: #e85808; */
}

.brochure-tab a {
    display: block;
    padding: 10px 20px;
    height: 100;
    background-color:rgb(235, 147, 39);
    text-align: center;
    text-decoration: none;
    color: #000; /* Set the text color */
    border-radius: 5px;
    transition: background-color 0.3s ease; /* Smooth transition for hover effect */
}

.brochure-tab a:hover {
    background-color:#e85808; /* Change background color on hover */
}


</style>

<!-- <div class="brochure-container">
  <div class="brochure-tab">
      <a href="{% static 'home/assets/pdf/RIC24 Invitation Brochure.pdf' %}">RIC24 Invitation Brochure</a>
  </div>
  <div class="brochure-tab">
      <a href="{% static 'home/assets/pdf/ABSTRACT.pdf' %}">ABSTRACT</a>
  </div>
  <div class="brochure-tab">
      <a href="{% static 'home/assets/pdf/Sponsors brochure.pdf' %}">Sponsors brochure</a>
  </div>
</div> -->




<h2>
   <center>Institute Speakers</center>
</h2>
<div class="wrapper" style="display: flex; flex-wrap: wrap; justify-content: space-around;">
   {% for i in speaker_list %}
       <!-- <a class="card" href="{% url 'event:speakerdetail' i.id %}"> -->
         <!-- <div class="card-banner"> -->
           <!-- <p class="category-tag technology">{{i.name}}</p> -->

            <!-- <p class="category-tag-right psycology">{{i.position}}</p> -->
           <!-- <img class="banner-img" src='{{i.pic.url}}' alt='Speaker'> -->
         <!-- </div> -->
         <!-- <div class="card-body" style="margin-top:100px"> -->
           <!-- <h2 class="blog-title">{{i.subtitle|safe}}</h2> -->
            <!-- <p class="blog-description">Looking to upgrade your gear? Here is the list of the best photography tools for this year</p> -->
           <!-- <div class="card-profile"> -->
             <!-- <img class="profile-img" src='{{i.pic.url}}' alt=''> -->
             <!-- <div class="card-profile-info"> -->
               <!-- <h3 class="profile-name">{{i.name}}</h3> -->
                <!-- <p class="profile-followers">45.7k followers</p> -->
             <!-- </div> -->
           <!-- </div> -->
         <!-- </div> -->
       <!-- </a> -->
        <div style="flex: 1 1 0; padding: 20px ;min-width: 400px; max-width: 480px; max-height: 900px; overflow: hidden">
           <a href="{% url 'event:speakerdetail' i.id %}">
                <div class="lgx-single-speaker speaker"> <!--lgx-single-speaker-circle lgx-single-speaker2 lgx-single-speaker3 -->
                   <center>
                       <figure>
                           <a class=""><img src="{{i.pic.url}}" alt="Speaker" width="relative" height="300px"/></a>
                           <h3 class="title">{{i.name}}</a></h3>
                           <h4 class="subtitle">{{i.subtitle|safe}}</h4>
                       </figure>
                   </center>
                    <!-- <p class="speaker-info" style="font-size: 1.6rem;text-align: justify;">
                    {{i.content|safe|linebreaks}}
                    </p> -->
                    <!-- <button class="rm">Read more</button> -->
               </div>
           </a>
        </div>

   {% endfor %}
</div>


<h2>
   <center>Department Speakers</center>
</h2>
<div class="" style="display: flex; flex-wrap: wrap; justify-content: space-around;">
   {% for i in dept_speaker_list %}
       <a class="card" href="{% url 'event:deptspeakerdetail' i.id %}">
         <div class="card-banner">
           <p class="category-tag popular">{{i.name}}</p>
           <p class="category-tag-right technology">{{i.dept}}</p>
           <img class="banner-img" src='{{i.pic.url}}' alt='Speaker'>
         </div>
         <div class="card-body">
           <h2 class="blog-title">{{i.subtitle|safe}}</h2>
            <p class="blog-description">Looking to upgrade your gear? Here is the list of the best photography tools for this year</p>
           <div class="card-profile">
             <img class="profile-img" src='{{i.pic.url}}' alt=''>
             <div class="card-profile-info">
               <h3 class="profile-name">{{i.name}}</h3>
                <p class="profile-followers">45.7k followers</p>
             </div>
           </div>
         </div>
       </a>

   {% endfor %}
</div>


{% endblock content %}