RIC/RIC/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
# from . import views

admin.site.site_header = "RIC Admin"
admin.site.site_title = "RIC Admin Portal"
admin.site.index_title = "Welcome to RIC ADMIN PORTAL"


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    # path('microsoft-login/', views.microsoft_login.as_view(), name='microsoft_login'),

    path('', include('home.urls')),
    path('editor/', include('editor.urls')),
    path('rc/', include('prev_edition.urls')),
    path('profile/', include('members.urls')),
    path('event/', include('event.urls')),
    path('team/', include('team.urls')),
    path('faq/', include('faq.urls')),
    path('sponsor/', include('sponsor.urls')),
    path('schedule/', include('schedule.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

RIC/members/urls.py
from django.urls import path, reverse_lazy
from . import views


app_name='members'
urlpatterns = [
    path('', views.ProfileListView.as_view(),name='all'),
    path('send-work-info/', views.send_workshop, name='send_workshop'),
    path('update-ic/', views.update_ic_fees, name='update_ic_fees'),
    path('pay/', views.send_payment, name='payment'),
    path('pay-empre/', views.send_payment_empre, name='payment_empre'),
    path('update-user-info/', views.update_workshop_bio, name='update_user_info'),
    path('registration_stats/', views.registrations_count, name='registration_stats'),
    path('update_names_and_emails/', views.update_names_and_emails, name='update_names_and_emails'),
    path('update-bio-events/', views.update_bio_events, name='update_bio_events'),
    path('send-preRIC/', views.send_instructions, name='send_preRIC'),
    path('send-institute-invitation/', views.send_institute_invitation, name='send_institute_invitation'),
    path('send-speaker-invitation/', views.send_speaker_invitation, name='send_speaker_invitation'),
    path('change-all/', views.change_all, name='change_all'),
    path('send-mail/', views.send_mail_to_selected_participants, name='send_mail'),
    # path('register/', views.ProfileCreateView.as_view(),name='create'),
   path('register/', views.ProfileRICCreateView.as_view(),name='create'),
#     path('register/', views.closed_view,name='create'),
    path('icregister/', views.ProfileICCreateView.as_view(),name='iccreate'),
    path('workshop_create/', views.WorkshopCreateView.as_view(),name='workshop_create'),
    path('accommodation_create/', views.AccommodationCreateView.as_view(),name='accommodation_create'),
    path('accommodation_detail/<int:pk>/', views.AccommodationDetailView.as_view(),name='accommodation_detail'),
    path('integrationBee/', views.IntegrationBeeCreateView.as_view(),name='integrationBee_create'),
    path('integrationBee/<int:pk>/', views.IntegrationBeeDetailView.as_view(),name='integrationBee_detail'),
#     path('dsinoQuation/', views.DifferentiaChallengeCreateView.as_view(),name='differentiaChallenge_create'),
#     path('dsinoQuation/<int:pk>/', views.DifferentiaChallengeDetailView.as_view(),name='differentiaChallenge_detail'),
#     path('mathOlympics/', views.MathEventCreateView.as_view(),name='mathEvent_create'),
#     path('mathOlympics/<int:pk>/', views.MathEventDetailView.as_view(),name='mathEvent_detail'),
#     path('mathOlympicsInd/', views.MathEventIndCreateView.as_view(),name='mathEventInd_create'),
#     path('mathOlympicsInd/<int:pk>/', views.MathEventIndDetailView.as_view(),name='mathEventInd_detail'),
    path('stud_detail/<int:pk>', views.StudDetailUpdateView.as_view(),name='stud_detail'),
    path('id_card/<int:pk>', views.IDUpdateView.as_view(),name='id_card'),
    path('detail/<int:pk>/', views.ProfileDetailView.as_view(),name='detail'),
    path('ric-detail/<int:pk>/', views.ProfileRICDetailView.as_view(),name='ric-detail'),
    path('detail/ic/<int:pk>/', views.ProfileICDetailView.as_view(),name='icdetail'),
    path('workshop_detail/<int:pk>/', views.WorkshopDetailView.as_view(),name='workshop_detail'),
    path('abstract/<int:pk>', views.AbstractUpdateView.as_view(),name='abstract'),
    path('ic_abstract/<int:pk>', views.AbstractICUpdateView.as_view(),name='ic_abstract'),
    path('re-upload-abstract/<int:pk>', views.AbstractRICUpdateView.as_view(),name='ric-abstract'),
    path('success',views.success, name='success'),
    path('mail/', views.mail, name='mail'),

]

RIC/members/views.py
import json
from django.http.response import Http404, HttpResponse, JsonResponse
from django.shortcuts import render
from django.views import View
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from .models import Event1,Event2,RICEvent, IC, ICEvent,WorkshopBio,IntegrationBee,MathEvent, MathEventIndividual,DifferentiaChallenge,Accommodation
from .forms import RICForm,ICForm ,AbstractForm,AbstractICForm,AbstractRICForm,WorkshopForm,AccommodationForm,IntegrationBeeForm,MathEventForm, MathEventIndividualForm,IDForm, StudDetailForm,DifferentiaChallengeForm,FullPaperSubmissionForm
import razorpay
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import TemplateView,ListView, DetailView, CreateView, UpdateView,DeleteView
from django.urls import reverse_lazy,reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import EmailMessage
from django.template.loader import render_to_string
from django.conf import settings

# Create your views here.

import pandas as pd
import pdfkit
import os
from django.db.models import Count
from django.contrib.auth import get_user_model


def send_workshop(request):
    tt = "AI for All: Bootcamp"
    bio_participants = WorkshopBio.objects.filter(workshop__title=tt)
    if not bio_participants:
        return HttpResponse("Emails Not found")

    messages = []
    for participant in bio_participants:

        email = participant.owner.email
        username = participant.owner.username
        events = tt
        msg = events
        name = participant.name
        time = "14 May, 2023 03:00 PM to 06:00 PM"
        venue = "5G3, Classroom Complex"

        subject = "Workshop Information for RIC'23"
        context = {'subject': subject,'name':name,'events':events,'username':username,'venue':venue,'time':time,}
        html_template = 'workshop_mail.html'
        html_message = render_to_string(html_template, context=context)

        message = EmailMessage(
            subject=subject,
            body=html_message,
            from_email=settings.EMAIL_HOST_USER,
            to=[email],

            cc=["c.chetan@iitg.ac.in","ihussain@iitg.ac.in","dprangan@iitg.ac.in","k.kalpana@iitg.ac.in","v.bhargava@iitg.ac.in","hiteshiit4@gmail.com",],
            reply_to=[settings.EMAIL_HOST_USER],
        )
        message.content_subtype = 'html'
        messages.append(message)


    count = len(messages)
    if count > 0:
        connection = get_connection()
        sent = connection.send_messages(messages)
        connection.close()
        return HttpResponse(f"Emails sent: {sent}/{count}")
        # return HttpResponse(f"Emails sent: {count} {msg}")
    else:
        return HttpResponse("No emails to send.")



def send_payment_empre(request):
    bio_participants = IC.objects.filter(event__name='EMPRENDIMIENTO')
    if not bio_participants:
        return HttpResponse("Emails Not found")

    messages = []
    for participant in bio_participants:

        email = participant.owner.email
        username = participant.owner.username
        events = participant.event
        name = participant.owner.username
        role = participant.role
        fee = participant.total/100

        subject = "Payment Information for RIC'23"
        context = {'subject': subject,'name':name,'events':events,'username':username,'role':role,'fee':fee,}
        html_template = 'payment_mail.html'
        html_message = render_to_string(html_template, context=context)

        message = EmailMessage(
            subject=subject,
            body=html_message,
            from_email=settings.EMAIL_HOST_USER,
            to=[email],
            cc=["c.chetan@iitg.ac.in",],
            # cc=["c.chetan@iitg.ac.in","ihussain@iitg.ac.in","dprangan@iitg.ac.in","k.kalpana@iitg.ac.in","v.bhargava@iitg.ac.in","hiteshiit4@gmail.com",],
            reply_to=[settings.EMAIL_HOST_USER],
        )
        message.content_subtype = 'html'
        messages.append(message)


    count = len(messages)
    if count > 0:
        connection = get_connection()
        sent = connection.send_messages(messages)
        connection.close()
        return HttpResponse(f"Emails sent: {sent}/{count}")
    else:
        return HttpResponse("No emails to send.")



def update_ic_fees(request):
    # Filter participants with "EMPRENDIMIENTO" event
    participants = IC.objects.filter(event__name="EMPRENDIMIENTO")

    # Update fees for each participant
    for participant in participants:
        participant.total = 50000  # Update fee to 1000 (or whatever value you want)
        participant.save()

    return HttpResponse(f"Fees updated for {len(participants)} participants.")



def registrations_count(request):
    events = Event1.objects.all()
    counts = {}
    for event in events:
        ric_reg = RICEvent.objects.filter(event=event).distinct('email')
        counts[event.name] = ric_reg.count()

    return render(request, 'members/registrations_count.html', {'counts': counts})

def update_workshop_bio(request):
    bios = WorkshopBio.objects.all()
    ics = IC.objects.all()
    counts = 0
    for bio in bios:
        users = User.objects.filter(email=bio.owner.email)
        if users.exists():
            user = users.first()
            bio.email = user.email
            bio.name = user.get_full_name()
            bio.save()
            counts +=1
    iccounts = 0
    for bio in ics:
        users = User.objects.filter(email=bio.owner.email)
        if users.exists():
            user = users.first()
            bio.email = user.email
            bio.name = user.get_full_name()
            bio.save()
            iccounts +=1
    # return render(request, 'members/registrations_count.html', {'counts': counts})
    return HttpResponse(request,f"Fees updated for {counts} and ic {iccounts}")

User = get_user_model()

def update_names_and_emails(request):
    events = RICEvent.objects.all()
    count = 0
    for event in events:
        count+=1
        owner = User.objects.get(id=event.owner_id)
        if event.name == 'Name':
            event.name = owner.get_full_name()
            event.email = owner.email
        event.save()
    return HttpResponse("Names and emails updated successfully"+str(count))


def update_bio_events(request):
    status = False
    bios = Bio.objects.all()
    status_bio =  False
    status_ric = False
    run = False
    ric_count = 0
    bio_count = 0

    for bio in bios:
        status = True
        events = bio.event1.all()
        run = True
        bio_count += 1

        for event in events:
            # Check if the event has already been added to RICEvent
            ric_count += 1
            # if not ric_bio.ricevent_set.filter(event=event).exists():
            # Calculate the fee based on the role of the participant
            if bio.role == "Student":
                fee = event.fee
            elif bio.role == "Academician":
                fee = 3 * event.fee
            elif bio.role == "Industry Expert":
                fee = 6 * event.fee
            else:
                fee = 6 * event.fee

            # Create a new RICEvent entry
            ric_event = RICEvent(
                institute=bio.institute,
                dept=bio.dept,
                abstract=bio.abstract,
                abstractFormat=bio.abstractFormat,
                event=event,
                number=bio.number,
                role=bio.role,
                owner=bio.owner,
                text=bio.text,
                total=fee,
                selected=False,
                selected_oral=False,
                razorpay_payment_id=bio.razorpay_payment_id,
                iitg_student=bio.iitg_student,
                remarks=bio.remarks,
            )
            status_ric = True
            ric_event.save()

        status_bio = True
    return render(request, 'success.html', {'status':status,'bio_count':bio_count,'ric_count':ric_count,'run_status':run,'status_bio':status_bio,'status_ric':status_ric})


def send_institute_invitation(request):

    # Path to the files
    directory_path = os.path.join(settings.TEMPLATES[0]['DIRS'][0], 'institute-mail')
    excel_path = os.path.join(directory_path, 'file.xlsx')
    html_path = os.path.join(directory_path, 'institute-mail.html')

    # Load the data from the Excel file
    data = pd.read_excel(excel_path)

    # Loop through the data and generate a PDF for each row
    for index, row in data.iterrows():
        name = row['Name']
        to_email = row['Email']

        # create mail content
        mail_content = render_to_string(html_path, {'name': name})


        # Attach the PDF to the email
        subject = "Invitation for Research and Industrial Conclave Integration'23"
        email_from = settings.EMAIL_HOST_USER
        email = EmailMessage(
                subject=subject,
                body=mail_content,
                from_email=email_from,
                to = [to_email],
                bcc=[email_from],
                reply_to=[email_from],
            )

        email.content_subtype = 'html'

        # Attach the brochure to the email
        brochure_path = os.path.join(directory_path, 'Brochure Final.pdf')
        with open(brochure_path, 'rb') as brochure_file:
            email.attach('Brochure Final.pdf', brochure_file.read(), 'application/pdf')

        # Send the email
        email.send()




    return render(request, 'success.html', {})


def send_speaker_invitation(request):
    # Path to the files
    directory_path = os.path.join(settings.TEMPLATES[0]['DIRS'][0], 'speaker-mail')
    excel_path = os.path.join(directory_path, 'file.xlsx')
    html_path = os.path.join(directory_path, 'speaker-mail.html')
    pdf_path = os.path.join(directory_path, 'Invitation letter.html')

    # Load the data from the Excel file
    data = pd.read_excel(excel_path)

RIC/members/templates/members/mathEventInd_detail.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<style>
  /* Import Font Dancing Script */
@import url(https://fonts.googleapis.com/css?family=Dancing+Script);

* {
    margin: 0;
}

body {
    background-color: #e8f5ff;
    font-family: Arial;
}

/* NavbarTop */
.navbar-top {
    background-color: #fff;
    color: #333;
    box-shadow: 0px 4px 8px 0px grey;
    height: 70px;
}

.title {
    font-family: 'Dancing Script', cursive;
    padding-top: 15px;
    position: absolute;
    left: 45%;
}

.navbar-top ul {
    float: right;
    list-style-type: none;
    margin: 0;
    overflow: hidden;
    padding: 18px 50px 0 40px;
}

.navbar-top ul li {
    float: left;
}

.navbar-top ul li a {
    color: #333;
    padding: 14px 16px;
    text-align: center;
    text-decoration: none;
}

.icon-count {
    background-color: #ff0000;
    color: #fff;
    float: right;
    font-size: 11px;
    left: -25px;
    padding: 2px;
    position: relative;
}

/* End */

/* Sidenav */
.sidenav {
    background-color: #fff;
    color: #333;
    border-bottom-right-radius: 25px;
    height: 86%;
    left: 0;
    overflow-x: hidden;
    padding-top: 20px;
    position: absolute;
    top: 70px;
    width: 250px;
}

.profile {
    margin-bottom: 20px;
    margin-top: -12px;
    text-align: center;
}

.profile img {
    border-radius: 50%;
    box-shadow: 0px 0px 5px 1px grey;
}

.name {
    font-size: 20px;
    font-weight: bold;
    padding-top: 20px;
}

.job {
    font-size: 16px;
    font-weight: bold;
    padding-top: 10px;
}

.url, hr {
    text-align: center;
}

.url hr {
    margin-left: 20%;
    width: 60%;
}

.url a {
    color: #818181;
    display: block;
    font-size: 20px;
    margin: 10px 0;
    padding: 6px 8px;
    text-decoration: none;
}

.url a:hover, .url .active {
    background-color: #e8f5ff;
    border-radius: 28px;
    color: #000;
    margin-left: 14%;
    width: 65%;
}

/* End */

/* Main */
.main {
    margin-top: 2%;
    margin-left: 23%;
    font-size: 28px;
    padding: 0 10px;
    width: 58%;
}

.main h2 {
    color: #333;
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    font-size: 24px;
    margin-bottom: 10px;
}

.main .card {
    background-color: #fff;
    border-radius: 18px;
    box-shadow: 1px 1px 8px 0 grey;
    height: auto;
    /* height: 2000px; */
    margin-bottom: 20px;
    padding: 20px 0 20px 50px;
}

.main .card table {
    border: none;
    font-size: 50%;
    height: auto;
    width: 80%;
}

.edit {
    position: absolute;
    color: #e7e7e8;
    right: 14%;
}

.social-media {
    text-align: center;
    width: 90%;
}

.social-media span {
    margin: 0 10px;
}

.fa-facebook:hover {
    color: #4267b3 !important;
}

.fa-twitter:hover {
    color: #1da1f2 !important;
}

.fa-instagram:hover {
    color: #ce2b94 !important;
}

.fa-invision:hover {
    color: #f83263 !important;
}

.fa-github:hover {
    color: #161414 !important;
}

.fa-whatsapp:hover {
    color: #25d366 !important;
}

.fa-snapchat:hover {
    color: #fffb01 !important;
}

/* End */
</style>
{% endblock css %}

{% block banner %}
<section>
  <div class="lgx-banner lgx-banner-music">
    <div class="lgx-banner-style">
      <div class="lgx-inner lgx-inner-fixed">
        <div class="container">
          <div class="row">
            <h1>Your Registration Info</h1>
          </div>
        </div>
      </div>
      <!--//.ROW-->
    </div>
    <!-- //.CONTAINER -->
  </div>
  <!-- //.INNER -->
  </div>
  </div>
</section>
{% endblock banner %}
{% block content %}
<div class="main">
  <h2>General Information</h2>
  <div class="card">
      <div class="card-body">
          <i class="fa fa-pen fa-xs edit"></i>
          <table>
              <tbody>
                  <tr>
                      <td>Unique ID</td>
                      <td>:</td>
                      <td>{{object.unique_id}}</td>
                  </tr>
                  <tr>
                      <td>Name</td>
                      <td>:</td>
                      <td>{{object.name}}</td>
                  </tr>
                  <tr>
                      <td>Email</td>
                      <td>:</td>
                      <td>{{user.email}}</td>
                  </tr>
                  <tr>
                      <td>Phone no.</td>
                      <td>:</td>
                      <td>{{object.number}}</td>
                    </tr>
                    <tr>
                        <td>Class</td>
                        <td>:</td>
                        <td>{{object.class_name}}</td>
                    </tr>
                  <tr>
                      <td>School Name</td>
                      <td>:</td>
                      <td>{{object.school_name}}</td>
                  </tr>
                  <tr>
                      <td>School Address</td>
                      <td>:</td>
                      <td>{{object.school_address}}</td>
                  </tr>
                  <tr>
                      <td>School Phone no.</td>
                      <td>:</td>
                      <td>{{object.school_contact}}</td>
                    </tr>
                  <tr>
                    <td> Selected</td>
                      <td>:</td>
                      <td >
                        {% if object.selected %}
                          <p id="blink">Successfully Registered<p>
                        {% else %}
                            Not Selected
                        {% endif %}
                            {% comment %} {{object.selected}} {% endcomment %}
                        </td>
                  </tr>

              </tbody>
          </table>
      </div>
  </div>


    <h2>Remarks </h2>
  <div class="card">
      <div class="card-body">
          <i class="fa fa-pen fa-xs edit"></i>
          <table>
              <tbody>
                    <tr>
                        <td>Remarks</td>
                        <td>:</td>
                        <td><a href="{% url 'members:stud_detail' object.id %}">{{object.remarks}}</a></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>

{% if object.selected %}
<h2>Selected </h2>

<h2>Instructions for event </h2>
<div class="card">
    <div class="card-body">
        <i class="fa fa-pen fa-xs edit"></i>
       <p>{{object.text|safe}}</p>
      </div>
  </div>

{% endif %}

</div>


<br><br>

<script type="text/javascript">
    var blink = document.getElementById('blink');
    setInterval(function() {
        blink.style.opacity = (blink.style.opacity == 0 ? 1 : 0);
    }, 100);
</script>
{% endblock content %}

RIC/members/templates/members/profile_list.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
<style>
  .userdet{
    margin: 1vw 12vw;
  }
  .userdetail{
    color: rgb(99, 144, 220); 
    font-size: 2vw; 
    font-weight: 600;
  }
  @media screen and (max-width:800px) {
    .userdet{
      margin: 1vw 1vw;
    }
    .userdetail{
      font-size: 3vw;
    }
  }
  @media screen and (max-width:600px) {
    .userdet{
      margin: 1vw 1vw;
    }
    .userdetail{
      font-size: 4.3vw;
    }
  }

</style>

{% endblock css %}
{% block banner %}
<section>
  <div class="lgx-banner lgx-banner-music">
    <div class="lgx-banner-style">
      <div class="lgx-inner lgx-inner-fixed">
        <div class="container">
          <div class="row">
            <h1>Your Registration Profile</h1>
          </div>
        </div>
      </div>
      <!--//.ROW-->
    </div>
    <!-- //.CONTAINER -->
  </div>
  <!-- //.INNER -->
  </div>
  </div>
</section>
{% endblock banner %}




{% block content %}

{% if user.is_authenticated %}
  <div class="userdet">
    <p class="userdetail" >Name : {{user.get_full_name}} </p>
    <p class="userdetail" >Email : {{user.email}} </p>
  </div>
{% endif %}

<!-- {% if bio_list %}

<div class="container">
  <div class="row">
    <br>
    <h1>
      Registration for Oral, Poster, Model
    </h1>
          {% for i in bio_list %}
            {% if i.owner == request.user %}
              <div class="col-sm-6">
                <div class="card">
                  <div class="card-body">
                    <h5 class="card-title">{{i.dept}} from {{i.institute}}</h5>
                    <p class="card-text">You have participated in {% for j in i.event1.all %}{{j}} <b>;</b> {% endfor %} </p>
                    <p class="card-text">For Payment, Abstract Submission Status and Instruction related info click below</p>
                    <a href="{% url 'members:detail' i.id %}" class="btn btn-primary">Click Here</a>
                  </div>
                </div>
              </div>
            {% endif %}
          {% endfor %}
  </div>
  <br>
</div>
{% endif %} -->

{% if ric_list %}

<div class="container">
  <div class="row">
    <br>
    <h1>
      Registration for Oral, Poster, Model
    </h1>
          {% for i in ric_list %}
            {% if i.owner == request.user %}
              <div class="col-sm-6">
                <div class="card">
                  <div class="card-body">
                    <h5 class="card-title">{{i.dept}} from {{i.institute}}</h5>
                    <p class="card-text">You have participated in <button type="button" class="btn btn-success">{{i.event}}</button> </p>
                    <p class="card-text">For Payment, Abstract Submission Status and Instruction related info click below</p>
                    <a href="{% url 'members:ric-detail' i.id %}" class="btn btn-primary">Click Here</a>
                  </div>
                </div>
              </div>
            {% endif %}
          {% endfor %}
  </div>
  <br>
</div>
{% endif %}

  {% if ic_list %}
  <div class="container">
    <div class="row">
      <br>
      <h1>
        Registration for Industrial Events
      </h1>
      {% for i in ic_list %}
        {% if i.owner == request.user %}
          <div class="col-sm-6">
            <div class="card">
              <div class="card-body">
                <h5 class="card-title">{{i.dept}} from {{i.institute}}</h5>
                <p class="card-text">You have participated in <button type="button" class="btn btn-success">{{i.event}}</button> </p>
                <p class="card-text">For Payment, Status and Instruction related info click below</p>

                <a href="{% url 'members:icdetail' i.id %}" class="btn btn-primary">Click Here</a>
              </div>
            </div>
          </div>
        {% endif %}
      {% endfor %}
    </div>
    <br>
  </div>
{% endif %}

{% if workshop_bio%}
<div class="container">
  <div class="row">
    <br>
    <h1>
      Registration for Workshop
    </h1>
    {% for i in workshop_bio %}

    {% if i.owner == request.user %}
      <div class="col-sm-6">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">{{i.dept}}</h5><button type="button" class="btn btn-primary">Workshop</button>
            <p class="card-text">For Payment and Instruction related info click below</p>
            <a href="{% url 'members:workshop_detail' i.id %}" class="btn btn-primary">Click to know details</a>
          </div>
        </div>
      </div>

      {% endif %}

      {% endfor %}
  </div>
  <br>
</div>
{% endif %}

{% comment %} {% debug %} {% endcomment %}
{% comment %} length intBee = {{ intBee|length }}
<br>
length diffChall = {{ diffChall|length }}
<br>
length mathEve = {{ mathEve|length }}
<br> {% endcomment %}

{% if intBee %}
<div class="container">
  <div class="row">
    <br>
    <h1>
      Registration for Integration Bee
    </h1>
    {% for i in intBee %}

      {% if i.owner == request.user %}
        <div class="col-sm-6">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">{{i.school_college_name}}</h5>
              {% comment %} <p class="card-text">You have participated in {{i.event2}},{% for j in i.event1.all %}{{j}}{% endfor %}</p> {% endcomment %}
              <p class="card-text">For Payment and other Instruction related info click below</p>
              <a href="{% url 'members:integrationBee_detail' i.id %}" class="btn btn-primary">Click to know details</a>
            </div>
          </div>
        </div>

        {% endif %}

      {% endfor %}
  </div>
  <br>
</div>
{% endif %}

{% if diffChall %}
<div class="container">
  <div class="row">
    <br>
    <h1>
      Registration for D'SinoQuation
    </h1>
    {% for i in diffChall %}

    {% if i.owner == request.user %}
      <div class="col-sm-6">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">{{i.school_college_name}}</h5>
            {% comment %} <p class="card-text">You have participated in {{i.event2}},{% for j in i.event1.all %}{{j}}{% endfor %}</p> {% endcomment %}
            <p class="card-text">For Payment and other Instruction related info click below</p>
            <a href="{% url 'members:differentiaChallenge_detail' i.id %}" class="btn btn-primary">Click to know details</a>
          </div>
        </div>
      </div>

      {% endif %}

      {% endfor %}
  </div>
  <br>
</div>
{% endif %}

{% if mathEve or mathEveInd %}
<div class="container">
  <div class="row">
    <br>
    <h1>
      Registration for Maths Olympics
    </h1>
    {% for i in mathEve %}

    {% if i.owner == request.user %}
      <div class="col-sm-6">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">{{i.school_name}}</h5>
            {% comment %} <p class="card-text">You have participated in {{i.event2}},{% for j in i.event1.all %}{{j}}{% endfor %}</p> {% endcomment %}
            <p class="card-text">For Payment and other Instruction related info click below</p>
            <a href="{% url 'members:mathEvent_detail' i.id %}" class="btn btn-primary">Click to know details</a>
          </div>
        </div>
      </div>

      {% endif %}

      {% endfor %}
      {% for i in mathEveInd %}

    {% if i.owner == request.user %}
      <div class="col-sm-6">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">{{i.name}}</h5>
            {% comment %} <p class="card-text">You have participated in {{i.event2}},{% for j in i.event1.all %}{{j}}{% endfor %}</p> {% endcomment %}
            <p class="card-text">For Payment and other Instruction related info click below</p>
            <a href="{% url 'members:mathEventInd_detail' i.id %}" class="btn btn-primary">Click to know details</a>
          </div>
        </div>
      </div>

      {% endif %}

      {% endfor %}
  </div>
  <br>
</div>
{% endif %}


{% if mathEve %}
<div class="container">
  <div class="row">
    <br>
    <h1>
      Accommodation Details
    </h1>
    {% for i in accommo %}

    {% if i.owner == request.user %}
      <div class="col-sm-6">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">{{i.owner}}</h5>
            {% comment %} <p class="card-text">You have participated in {{i.event2}},{% for j in i.event1.all %}{{j}}{% endfor %}</p> {% endcomment %}
            <p class="card-text">For Payment and other Instruction related info click below</p>
            <a href="{% url 'members:accommodation_detail' i.id %}" class="btn btn-primary">Click to know details</a>
          </div>
        </div>
      </div>

      {% endif %}

      {% endfor %}
  </div>
  <br>
</div>
{% endif %}



{% endblock content %}

RIC/members/templates/members/registrations_count.html
{% for event, count in counts.items %}
    <p>{{ event }}: {{ count }}</p>
{% endfor %}

RIC/members/templates/members/success.html
<h1>Success</h1>