RIC/RIC/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
# from . import views

admin.site.site_header = "RIC Admin"
admin.site.site_title = "RIC Admin Portal"
admin.site.index_title = "Welcome to RIC ADMIN PORTAL"


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    # path('microsoft-login/', views.microsoft_login.as_view(), name='microsoft_login'),

    path('', include('home.urls')),
    path('editor/', include('editor.urls')),
    path('rc/', include('prev_edition.urls')),
    path('profile/', include('members.urls')),
    path('event/', include('event.urls')),
    path('team/', include('team.urls')),
    path('faq/', include('faq.urls')),
    path('sponsor/', include('sponsor.urls')),
    path('schedule/', include('schedule.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

RIC/editor/urls.py
from django.urls import path
from .views import ViewAllRICEventsView, ChangeStatusView, ViewRICEventSubmissionView

app_name = 'editor'

urlpatterns = [
    path('', ViewAllRICEventsView.as_view(), name='view_all_ricevents'),
    path('change_status/<int:event_id>/', ChangeStatusView.as_view(), name='change_status'),
    path('view/<int:event_id>/', ViewRICEventSubmissionView.as_view(), name='view_submission'),
]

RIC/templates/admin-base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

    <!-- Add your head content here -->
    <title>
        {% block title %}{% endblock %}
    </title>

    <!-- GOOGLE FONT -->
    <link rel="stylesheet" type="text/css"
          href="https://fonts.googleapis.com/css?family=Oswald:400,700%7cRaleway:300,400,400i,500,600,700,900" />

    <!-- MASTER  STYLESHEET  -->
    <link id="lgx-master-style" rel="stylesheet" href="{% static 'home/assets/css/style-default.min.css' %}"
          media="all" />

    <!-- MODERNIZER CSS  -->
    <script src="{% static 'home/assets/js/vendor/modernizr-2.8.3.min.js' %}"></script>

    <script src="{% static 'home/assets/js/vendor/modernizr-2.8.3.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>


</head>
<body>
<nav class="col-md-2 d-none d-md-block bg-light sidebar">
    <div class="sidebar-sticky">
        <ul class="nav flex-column">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'editor:view_all_ricevents' %}?status=pending">
                    View All RIC Events (Pending)
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'editor:view_all_ricevents' %}?status=accepted">
                    View Accepted RIC Events
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'editor:view_all_ricevents' %}?status=rejected">
                    View Rejected RIC Events
                </a>
            </li>
        </ul>
    </div>
</nav>

<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
    <!-- Content area where specific page content will be included -->
    {% block content %}
    {% endblock %}
</main>

<!-- JQUERY  -->
<script src="{% static 'home/assets/js/vendor/jquery-1.12.4.min.js' %}"></script>

<!-- BOOTSTRAP JS  -->
<script src="{% static 'home/assets/libs/bootstrap/js/bootstrap.min.js' %}"></script>

<!-- Smooth Scroll  -->
<script src="{% static 'home/assets/libs/jquery.smooth-scroll.js' %}"></script>

<!-- SKILLS SCRIPT  -->
<script src="{% static 'home/assets/libs/jquery.validate.js' %}"></script>

<!-- adding magnific popup js library -->
<script type="text/javascript"
        src="{% static 'home/assets/libs/maginificpopup/jquery.magnific-popup.min.js' %}"></script>

<!-- Owl Carousel  -->
<script src="{% static 'home/assets/libs/owlcarousel/owl.carousel.min.js' %}"></script>

<!-- COUNTDOWN   -->
<script src="{% static 'home/assets/libs/countdown.js' %}"></script>
<script src="{% static 'home/assets/libs/timer/TimeCircles.js' %}"></script>

<!-- Counter JS -->
<script src="{% static 'home/assets/libs/waypoints.min.js' %}"></script>
<script src="{% static 'home/assets/libs/counterup/jquery.counterup.min.js' %}"></script>

<!-- SMOTH SCROLL -->
<script src="{% static 'home/assets/libs/jquery.smooth-scroll.min.js' %}"></script>
<script src="{% static 'home/assets/libs/jquery.easing.min.js' %}"></script>

<!-- type js -->
<script src="{% static 'home/assets/libs/typed/typed.min.js' %}"></script>

<!-- header parallax js -->
<script src="{% static 'home/assets/libs/header-parallax.js' %}"></script>

<!-- instafeed js -->
<!--<script src="https://cdnjs.cloudflare.com/ajax/libs/instafeed.js/1.4.1/instafeed.min.js"></script>-->
<script src="{% static 'home/assets/libs/instafeed.min.js' %}"></script>

<!-- CUSTOM SCRIPT  -->
<script src="{% static 'home/assets/js/custom.script.js' %}"></script>

<script type="text/javascript" src="{% static 'home/assets/js/cart.js' %}"></script>

</body>
</html>

RIC/templates/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <!-- Create register form using djangoforms -->
    Success
    <br />
    Status: {{ status }}
    <br />
    COUNT_BIO: {{ bio_count }}
    <br />
    COUNT_RIC: {{ ric_count }}
    <br />
    RUN: {{ run_status }}
    <br />
    BIO: {{ status_bio }}
    <br />
    RIC: {{ status_ric }}
</body>
</html>